_ulid: 01KXTB2VMTCBBC34292MEG49N4
slugs:
  - task-canvas-2-0-spatial-workspace
title: "Implement: Canvas 2.0 Spatial Workspace"
type: task
spec_ref: "@canvas-workspace"
derivation: auto
status: pending
blocked_by: []
depends_on: []
context: []
priority: 1
tags: []
vcs_refs: []
created_at: 2026-07-18T10:06:53.082Z
todos: []
