_ulid: 01KXTB2VW4XV2SE0NND7Y3173G
slugs:
  - task-mobile-workspace-projection
title: "Implement: Mobile Workspace Projection"
type: task
spec_ref: "@canvas-mobile-projection"
derivation: auto
status: pending
blocked_by: []
depends_on:
  - "@task-canvas-2-0-spatial-workspace"
context: []
priority: 1
tags: []
vcs_refs: []
created_at: 2026-07-18T10:06:53.316Z
todos: []
