_ulid: 01KXTB2VNHQRW9333PA35CFP3A
slugs:
  - task-spatial-scene-persistence
title: "Implement: Spatial Scene Persistence"
type: task
spec_ref: "@canvas-scene-persistence"
derivation: auto
status: pending
blocked_by: []
depends_on:
  - "@task-canvas-2-0-spatial-workspace"
context: []
priority: 1
tags: []
vcs_refs: []
created_at: 2026-07-18T10:06:53.105Z
todos: []
